name: Build DLT-daemon on Windows
 
on:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: windows-latest
 
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
 
      - name: Remove all GCC warning flags (-W...)
        shell: pwsh
        run: |
          Get-ChildItem -Recurse -Filter CMakeLists.txt | ForEach-Object {
            (Get-Content $_.FullName) `
              -replace "-W[a-zA-Z0-9\-]+", "" `
              | Set-Content $_.FullName
          }
 
      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.27.7'
 
      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64
 
      - name: Build
        run: cmake --build build --config Release
 
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: dlt-daemon
          path: build/Release/*.exe
